#ifndef ANKI_BRIDGE_H
#define ANKI_BRIDGE_H

/* Auto-generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new Anki backend instance.
 *
 * # Safety
 * - `init_data` must point to a valid buffer of `init_len` bytes containing a
 *   serialized `BackendInit` protobuf message, or be null for defaults.
 * - `out_ptr` must point to writable memory for a single `int64_t`.
 *
 * Returns 0 on success, -1 on error.
 */
int anki_open_backend(const uint8_t *init_data, uintptr_t init_len, int64_t *out_ptr);

/**
 * Execute a backend RPC method via protobuf.
 *
 * # Safety
 * - `backend_ptr` must be a valid pointer returned by `anki_open_backend`.
 * - `input_data`/`input_len` must describe a valid protobuf request (or be null/0).
 * - `out_data`/`out_len` receive the response. Caller MUST free with
 *   `anki_free_response`.
 *
 * Returns:
 *   0  on success (out_data has the response protobuf),
 *   1  on backend error (out_data has a serialized BackendError protobuf),
 *  -1  on FFI error (null backend pointer).
 */
int anki_run_method(int64_t backend_ptr,
                    uint32_t service,
                    uint32_t method,
                    const uint8_t *input_data,
                    uintptr_t input_len,
                    uint8_t **out_data,
                    uintptr_t *out_len);

/**
 * Free a response buffer allocated by `anki_run_method` / the named wrappers.
 *
 * # Safety
 * `data`/`len` must be a buffer previously produced by this library, or null/0.
 */
void anki_free_response(uint8_t *data, uintptr_t len);

/**
 * Close and destroy the backend instance.
 *
 * # Safety
 * `backend_ptr` must be a pointer from `anki_open_backend`; invalid afterwards.
 */
void anki_close_backend(int64_t backend_ptr);

/**
 * Open (or create) a collection at `collection_path`.
 *
 * This is the key proof-of-life call: it routes OpenCollection through the real
 * rslib backend, which opens/creates the SQLite collection on disk.
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend`.
 * - `collection_path` must be a valid NUL-terminated UTF-8 C string.
 * - `media_folder_path` / `media_db_path` may be null (empty) or NUL-terminated
 *   UTF-8 C strings.
 *
 * Returns 0 on success, 1 on backend error, -1 on FFI error (bad pointer/string).
 */
int anki_open(int64_t backend_ptr,
              const char *collection_path,
              const char *media_folder_path,
              const char *media_db_path);

/**
 * Fetch the currently queued cards as a serialized `QueuedCards` protobuf.
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend` with a collection already open.
 * - `out_data`/`out_len` receive the protobuf response; free with
 *   `anki_free_response`.
 *
 * Returns 0 on success, 1 on backend error (out has BackendError), -1 on FFI error.
 */
int anki_get_queued_cards(int64_t backend_ptr,
                          uint32_t fetch_limit,
                          uint8_t **out_data,
                          uintptr_t *out_len);

/**
 * Answer a card. `card_answer_data` is a serialized `CardAnswer` protobuf.
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend` with a collection open.
 * - `card_answer_data`/`card_answer_len` must describe a valid `CardAnswer` proto.
 * - `out_data`/`out_len` receive the `OpChanges` protobuf; free with
 *   `anki_free_response`.
 *
 * Returns 0 on success, 1 on backend error, -1 on FFI error.
 */
int anki_answer_card(int64_t backend_ptr,
                     const uint8_t *card_answer_data,
                     uintptr_t card_answer_len,
                     uint8_t **out_data,
                     uintptr_t *out_len);

/**
 * Close the currently open collection.
 *
 * # Safety
 * `backend_ptr` must be from `anki_open_backend`.
 *
 * Returns 0 on success, 1 on backend error, -1 on FFI error.
 */
int anki_close(int64_t backend_ptr, bool downgrade_to_schema11);

/**
 * Import an .apkg package into the currently open collection via rslib's
 * ImportAnkiPackage RPC (BackendImportExportService svc 39 / method 2).
 *
 * Uses default options EXCEPT `with_scheduling = false`, so every imported
 * card enters as a fresh "new" card that is immediately due for review (we
 * want a study session today, not whatever schedule the deck was exported
 * with). `with_deck_configs = true` keeps the deck's own config.
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend` with a collection open.
 * - `package_path` must be a valid NUL-terminated UTF-8 C string.
 *
 * Returns 0 on success, 1 on backend error, -1 on FFI error (bad ptr/string).
 */
int anki_import_apkg(int64_t backend_ptr, const char *package_path);

/**
 * Select the deck with the given name as the current deck, so its cards (and
 * its children's cards) populate the scheduler queue.
 *
 * GetQueuedCards builds the study queue from the *currently selected* deck. A
 * freshly opened collection selects the Default deck, so after importing the
 * GMAT deck we must point the scheduler at it. Resolves the name to a DeckId
 * via GetDeckIdByName, then SetCurrentDeck (both BackendDecksService, svc 7).
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend` with a collection open.
 * - `deck_name` must be a valid NUL-terminated UTF-8 C string.
 *
 * Returns 0 on success, 1 on backend error / unknown deck, -1 on FFI error.
 */
int anki_select_deck_by_name(int64_t backend_ptr, const char *deck_name);

/**
 * Fetch the next queued card, render it through rslib, and return a small JSON
 * blob describing it. The card's SchedulingStates are stashed in `states_store`
 * keyed by card_id so a later `anki_answer_rating` can rebuild the CardAnswer.
 *
 * Output JSON (UTF-8, caller frees with `anki_free_response`):
 *   {"card_id":123,"question":"<html>","answer":"<html>","css":"..."}
 * When the queue is empty, returns: {"empty":true}
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend` with a collection open.
 * - `out_data`/`out_len` receive the JSON bytes; free with `anki_free_response`.
 *
 * Returns 0 on success (incl. empty queue), 1 on backend error, -1 on FFI error.
 */
int anki_next_card(int64_t backend_ptr, uint8_t **out_data, uintptr_t *out_len);

/**
 * Compute the three GMAT scores (memory / performance / readiness) and return
 * them as a JSON blob (caller frees with `anki_free_response`). Scoped to the
 * whole collection (the phone/desktop use a single GMAT deck).
 *
 * Output JSON: {"memory":SV,"performance":SV,"readiness":SV} where each SV is
 * {"abstained":bool,"score":f,"low":f,"high":f,"unit":"pct|gmat",
 *  "confidence":"","reasons":[..],"missing":[..]}.
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend` with a collection open.
 * - `out_data`/`out_len` receive the JSON bytes; free with `anki_free_response`.
 *
 * Returns 0 on success, 1 on backend error, -1 on FFI error.
 */
int anki_get_scores(int64_t backend_ptr, uint8_t **out_data, uintptr_t *out_len);

/**
 * Auto-grade a tapped multiple-choice answer into an Anki ease (1..=4) using the
 * shared engine: the rating comes from correctness × the student's confidence
 * (not from time). Pair the result with `anki_answer_rating` to record the
 * review. The caller can derive the "overconfident miss" flag itself (wrong +
 * confidence > 0); the desktop path reads it from the RPC response.
 *
 * `correct`: 0 = wrong, non-zero = right. `confidence`: 0 = guessing,
 * 1 = fairly sure, 2 = confident.
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend` with a collection open.
 *
 * Returns the ease 1..=4 on success; -1 on FFI error, -2 on backend error,
 * -3 on decode error.
 */
int anki_grade_answer(int64_t backend_ptr, uint8_t correct, uint32_t confidence);

/**
 * Answer the given card with a rating, rebuilding the CardAnswer from the
 * SchedulingStates rslib returned for that card in the prior `anki_next_card`.
 *
 * `rating`: 1=Again, 2=Hard, 3=Good, 4=Easy (the UI's natural 1..=4 order;
 * mapped to the proto enum AGAIN=0/HARD=1/GOOD=2/EASY=3 internally).
 *
 * # Safety
 * - `backend_ptr` must be from `anki_open_backend` with a collection open.
 *
 * Returns 0 on success, 1 on backend error, -1 on FFI error / unknown card /
 * invalid rating.
 */
int anki_answer_rating(int64_t backend_ptr, int64_t card_id, uint32_t rating);

/**
 * Log in to a sync server. Returns a serialized SyncAuth (caller frees via anki_free_response).
 * # Safety: standard FFI pointer contract; strings are NUL-terminated UTF-8.
 */
int anki_sync_login(int64_t backend_ptr,
                    const char *endpoint,
                    const char *user,
                    const char *pass,
                    uint8_t **out_data,
                    uintptr_t *out_len);

/**
 * Run a collection sync using a serialized SyncAuth from anki_sync_login.
 * Returns a serialized SyncCollectionResponse (inspect `.required` for full-sync).
 * # Safety: auth_data/auth_len describe a valid SyncAuth protobuf.
 */
int anki_sync_collection(int64_t backend_ptr,
                         const uint8_t *auth_data,
                         uintptr_t auth_len,
                         uint8_t **out_data,
                         uintptr_t *out_len);

/**
 * Full upload or download (used when SyncCollectionResponse.required is a full-sync variant).
 * upload=true -> full_upload; false -> full_download. server_usn < 0 omits media sync.
 * # Safety: auth_data/auth_len describe a valid SyncAuth protobuf.
 */
int anki_full_upload_or_download(int64_t backend_ptr,
                                 const uint8_t *auth_data,
                                 uintptr_t auth_len,
                                 bool upload,
                                 int32_t server_usn,
                                 uint8_t **out_data,
                                 uintptr_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ANKI_BRIDGE_H */
