#!/usr/bin/env python3
"""Provision the GMAT sync server + default account and emit ONE source-of-truth config.

This is the "do it on our end" script: instead of hand-typing a URL + username +
password into each app on every deploy, run ONE command here. It

  1. resolves (or deploys) the sync server,
  2. ensures the default sync ACCOUNT exists on it (via SYNC_USER1=user:pass),
  3. writes the resolved URL + credentials into a single config file
     (deploy/fly-sync/sync-config.json) that BOTH apps read their defaults from,
  4. verifies the server answers.

Both apps ship with these same values baked in as build-time defaults (see
sync-config.json and the README), so a fresh install syncs with ONE TAP and no
pasting. Re-running this after a redeploy just refreshes the one config file.

Targets
-------
  --target fly     (default) Use the stable fly.io app `gmat-sync`. The hostname
                   `https://gmat-sync.fly.dev/` is stable for the life of the app
                   (fly.io only recycles it if the app is destroyed), which is
                   exactly why we can bake it in. Deploys + sets the SYNC_USER1
                   secret when --deploy is passed and `fly` is authenticated.

  --target local   Run the fork's own `anki-sync-server` binary on this machine
                   (no fly.io account / billing needed). Emits a LAN URL. Good
                   for a fully offline demo, or when the fly trial is paused.

The password is hashed by the server with a FIXED salt (see
rslib/src/sync/http_server/mod.rs), so a given user:pass is reproducible across
every deploy — the baked-in default keeps working after any redeploy.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent  # .../speedrun
CONFIG_PATH = HERE / "sync-config.json"

# --- The single source of truth for the DEFAULT account -----------------------
# These are baked into both apps (see README "How the apps default to it").
# `demo` is a throwaway account on a self-hosted server that only holds this
# demo's GMAT collection, so shipping the password is fine for the assignment.
DEFAULT_APP = "gmat-sync"  # fly.io app name -> stable hostname gmat-sync.fly.dev
DEFAULT_FLY_URL = f"https://{DEFAULT_APP}.fly.dev/"
DEFAULT_USER = "demo"
DEFAULT_PASS = "gmatsync2026"
LOCAL_PORT = 27701  # fork's anki-sync-server default demo port


def log(msg: str) -> None:
    print(f"[provision] {msg}", flush=True)


def die(msg: str) -> None:
    print(f"[provision] ERROR: {msg}", file=sys.stderr, flush=True)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Health check (shared by both targets)
# ---------------------------------------------------------------------------
def wait_for_server(url: str, timeout: float = 40.0) -> bool:
    """Return True once the sync server answers at `url`.

    The Anki sync server has no dedicated /health route; any HTTP response
    (even 404) proves the process is up and reachable, which is all we need.
    """
    base = url.rstrip("/")
    deadline = time.time() + timeout
    last_err = ""
    while time.time() < deadline:
        for path in ("/health", "/"):
            try:
                req = urllib.request.Request(base + path, method="GET")
                with urllib.request.urlopen(req, timeout=5) as resp:
                    log(f"server responded {resp.status} at {path}")
                    return True
            except urllib.error.HTTPError as e:
                # A 4xx/5xx still means the server is up and speaking HTTP.
                log(f"server responded {e.code} at {path} (up)")
                return True
            except Exception as e:  # noqa: BLE001 - connection refused / DNS / timeout
                last_err = str(e)
        time.sleep(2)
    log(f"server did not answer within {timeout:.0f}s (last: {last_err})")
    return False


# ---------------------------------------------------------------------------
# Config emission
# ---------------------------------------------------------------------------
def write_config(url: str, user: str, password: str, target: str) -> None:
    """Write the ONE config the apps read their defaults from."""
    url = url if url.endswith("/") else url + "/"  # rslib does Url::join("sync/")
    config = {
        "_comment": (
            "Single source of truth for GMAT sync defaults. Regenerated by "
            "deploy/fly-sync/provision.py. Both apps bake these values in so "
            "sync is one tap with no pasting. Edit via the script, not by hand."
        ),
        "syncServerURL": url,
        "syncUser": user,
        "syncPass": password,
        "target": target,
        "generatedAt": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
    }
    CONFIG_PATH.write_text(json.dumps(config, indent=2) + "\n")
    log(f"wrote {CONFIG_PATH}")
    log(f"  URL={url}  user={user}")


# ---------------------------------------------------------------------------
# Target: fly.io (stable hostname)
# ---------------------------------------------------------------------------
def provision_fly(deploy: bool, verify: bool) -> None:
    url = DEFAULT_FLY_URL
    if not deploy:
        log(f"using stable fly.io hostname (no deploy): {url}")
        write_config(url, DEFAULT_USER, DEFAULT_PASS, target="fly")
        if verify:
            wait_for_server(url)
        _print_success(url, DEFAULT_USER, DEFAULT_PASS, "fly")
        return

    fly = shutil.which("fly") or shutil.which("flyctl")
    if not fly:
        die("`fly` not found. Install flyctl, or run with --target local.")

    # Auth check.
    who = subprocess.run([fly, "auth", "whoami"], capture_output=True, text=True)
    if who.returncode != 0:
        die("not logged in to fly. Run `fly auth login`, or use --target local.")
    log(f"fly account: {who.stdout.strip()}")

    # Push the fork so the Docker build fetches current sync-protocol code.
    anki = REPO_ROOT / "anki"
    if (anki / ".git").exists():
        log("pushing anki fork so fly builds current sync code…")
        subprocess.run(["git", "-C", str(anki), "push", "origin", "main"], check=False)

    # Set the default account as a fly secret (server reads SYNC_USER1=user:pass).
    secret = f"SYNC_USER1={DEFAULT_USER}:{DEFAULT_PASS}"
    log("setting SYNC_USER1 secret (default account)…")
    r = subprocess.run(
        [fly, "secrets", "set", secret, "--app", DEFAULT_APP, "--stage"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        # --stage may be unsupported on older flyctl; fall back to a plain set.
        subprocess.run([fly, "secrets", "set", secret, "--app", DEFAULT_APP], check=False)

    log("deploying…")
    dep = subprocess.run([fly, "deploy", "--app", DEFAULT_APP], cwd=str(HERE))
    if dep.returncode != 0:
        die(
            "fly deploy failed. If this is a billing/trial block, add a card at "
            "https://fly.io/trial, or run with --target local for a free demo."
        )

    write_config(url, DEFAULT_USER, DEFAULT_PASS, target="fly")
    if verify and not wait_for_server(url):
        die("deployed but server not answering; check `fly logs --app gmat-sync`.")
    _print_success(url, DEFAULT_USER, DEFAULT_PASS, "fly")


# ---------------------------------------------------------------------------
# Target: local (free, no fly account) — runs the fork's own binary
# ---------------------------------------------------------------------------
def _lan_ip() -> str:
    """Best-effort LAN IP so a physical phone on the same Wi-Fi can reach it."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))  # no packets sent; just picks the route
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:  # noqa: BLE001
        return "127.0.0.1"


def provision_local(run: bool, verify: bool) -> None:
    ip = _lan_ip()
    url = f"http://{ip}:{LOCAL_PORT}/"
    write_config(url, DEFAULT_USER, DEFAULT_PASS, target="local")

    if not run:
        log("wrote local config (not starting the server; pass --run to start it).")
        _print_success(url, DEFAULT_USER, DEFAULT_PASS, "local")
        log("start the server yourself with:")
        log(f"  {_local_cmd_hint()}")
        return

    anki = REPO_ROOT / "anki"
    env = dict(os.environ)
    env["SYNC_HOST"] = "0.0.0.0"
    env["SYNC_PORT"] = str(LOCAL_PORT)
    env["SYNC_USER1"] = f"{DEFAULT_USER}:{DEFAULT_PASS}"
    env.setdefault("SYNC_BASE", str(HERE / ".syncserver-data"))

    log("building + starting the fork's anki-sync-server locally…")
    log(f"  {url}  (Ctrl-C to stop)")
    proc = subprocess.Popen(
        ["cargo", "run", "--release", "-p", "anki-sync-server"],
        cwd=str(anki), env=env,
    )
    try:
        if verify and wait_for_server(url, timeout=180):
            _print_success(url, DEFAULT_USER, DEFAULT_PASS, "local")
            log("server is up; leaving it running. Ctrl-C to stop.")
        proc.wait()
    except KeyboardInterrupt:
        log("stopping server…")
        proc.terminate()


def _local_cmd_hint() -> str:
    return (
        f'SYNC_HOST=0.0.0.0 SYNC_PORT={LOCAL_PORT} '
        f'SYNC_USER1="{DEFAULT_USER}:{DEFAULT_PASS}" '
        f'cargo run --release -p anki-sync-server'
    )


# ---------------------------------------------------------------------------
def _print_success(url: str, user: str, password: str, target: str) -> None:
    log("=" * 64)
    log("DONE. Both apps default to these values (no pasting):")
    log(f"  server URL : {url}")
    log(f"  username   : {user}")
    log(f"  password   : {password}")
    log(f"  target     : {target}")
    log(f"  config     : {CONFIG_PATH}")
    log("=" * 64)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--target", choices=["fly", "local"], default="fly",
                   help="fly.io (stable hostname, default) or a local server.")
    p.add_argument("--deploy", action="store_true",
                   help="[fly] actually deploy + set the account secret "
                        "(default: just resolve the stable URL + write config).")
    p.add_argument("--run", action="store_true",
                   help="[local] build + start the server now.")
    p.add_argument("--no-verify", action="store_true",
                   help="skip the post-write health check.")
    args = p.parse_args()

    verify = not args.no_verify
    if args.target == "fly":
        provision_fly(deploy=args.deploy, verify=verify)
    else:
        provision_local(run=args.run, verify=verify)


if __name__ == "__main__":
    main()
