#!/usr/bin/env python3
"""AI difficulty calibration for the GMAT study app.

The app's traceable **AI feature**: an LLM rates each question's difficulty on a
fine-grained 0-100 scale with a one-line cited rationale, replacing the coarse
`difficulty::easy|medium|hard` tags (which become the baseline the AI must beat,
see eval_difficulty.py). Every rating is written to a sidecar file so it is
auditable — not a black box.

Outputs (never edits items.json in place, so it can't collide with content edits):
  * content/ai_difficulty.json  -- {item_id: {ai_difficulty, ai_difficulty_reason,
    rubric_version}} -- the traceable record.
  * (--apply-tags COL) writes an `aidiff::NN` tag onto each matching note in an
    Anki collection so the Rust engine (scheduler/adaptive.rs) can read it per
    card. Notes are matched by their existing `id::<item_id>` tag.

Model backend, in order of preference:
  1. ANTHROPIC_API_KEY set        -> Anthropic Python SDK (portable; what a grader uses).
  2. `claude` CLI on PATH         -> `claude -p` headless (uses Claude Code auth; no key).
  3. neither                      -> abort with instructions (use --dry-run to preview prompts).

NOTE: the ratings shipped tonight (content/ai_difficulty.json) were generated by a
fan-out of Claude agents applying THIS rubric, because no ANTHROPIC_API_KEY was
available in the build environment. This script reproduces them from a key/CLI and
is the canonical pipeline; the rubric below is the single source of truth.

Usage:
  python content/tools/calibrate_difficulty.py                 # rate all, write sidecar
  python content/tools/calibrate_difficulty.py --only Q-PS-001 # rate one
  python content/tools/calibrate_difficulty.py --force         # re-rate already-rated
  python content/tools/calibrate_difficulty.py --apply-tags /path/collection.anki2
  python content/tools/calibrate_difficulty.py --dry-run       # print prompts, no model call
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ITEMS_PATH = REPO / "content" / "items.json"
SIDECAR_PATH = REPO / "content" / "ai_difficulty.json"

RUBRIC_VERSION = "1.0"

RUBRIC = """Rate this GMAT question's difficulty for a test-taker on a 0-100 integer scale.

Judge against these factors:
- reasoning steps: number of distinct steps from stem to answer
- concept load: one concept vs several combined
- distractor trickiness: are the wrong choices engineered to catch common errors?
- parsing/wording: negations, "EXCEPT", convoluted stems
- computation weight: quick mental math vs heavy arithmetic
- intended time: the item's target_seconds is a difficulty signal

Anchor to these bands so ratings are comparable across the whole deck:
  0-20  trivial / 1-step recall
  20-40 straightforward single-concept
  40-60 moderate multi-step
  60-80 multi-step with a trap or combined concepts
  80-100 heavy multi-step with strong distractors
Place the item in the right band first, then fine-tune within it. Single-point
differences are not meaningful.

Respond with ONLY a JSON object, no prose around it:
{"ai_difficulty": <int 0-100>, "ai_difficulty_reason": "<one line naming the concrete driving factors for THIS item>"}
Example reason: "72 - 3-step ratios+percents chain; choice (C) is an off-by-one trap." """


def load_items() -> dict[str, dict]:
    """Return {id: item} regardless of whether items.json is a list, a dict of
    items, or a wrapper with an 'items' list."""
    d = json.loads(ITEMS_PATH.read_text())
    if isinstance(d, list):
        seq = d
    elif isinstance(d, dict) and isinstance(d.get("items"), list):
        seq = d["items"]
    elif isinstance(d, dict):
        seq = list(d.values())
    else:
        raise SystemExit("items.json: unrecognized shape")
    return {it["id"]: it for it in seq if isinstance(it, dict) and it.get("id")}


def build_prompt(item: dict) -> str:
    choices = item.get("choices") or []
    if isinstance(choices, dict):
        choices = [f"{k}) {v}" for k, v in choices.items()]
    return (
        f"{RUBRIC}\n\n"
        f"--- QUESTION ---\n"
        f"topic: {item.get('topic')}\n"
        f"type: {item.get('type')}\n"
        f"target_seconds: {item.get('target_seconds')}\n"
        f"stem: {item.get('stem')}\n"
        f"choices: {chr(10).join(str(c) for c in choices)}\n"
        f"correct answer: {item.get('answer')}\n"
    )


# ---- model backends -------------------------------------------------------

def _parse_rating(text: str) -> dict:
    """Pull the {ai_difficulty, ai_difficulty_reason} JSON object out of a reply."""
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        raise ValueError(f"no JSON object in model reply: {text[:200]!r}")
    obj = json.loads(m.group(0))
    diff = int(obj["ai_difficulty"])
    if not 0 <= diff <= 100:
        raise ValueError(f"ai_difficulty out of range: {diff}")
    return {"ai_difficulty": diff, "ai_difficulty_reason": str(obj["ai_difficulty_reason"]).strip()}


def rate_via_api(prompt: str, model: str) -> dict:
    import anthropic  # type: ignore

    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY
    msg = client.messages.create(
        model=model, max_tokens=300,
        messages=[{"role": "user", "content": prompt}],
    )
    return _parse_rating("".join(b.text for b in msg.content if b.type == "text"))


def rate_via_cli(prompt: str) -> dict:
    out = subprocess.run(
        ["claude", "-p", prompt], capture_output=True, text=True, timeout=120,
    )
    if out.returncode != 0:
        raise RuntimeError(f"claude CLI failed: {out.stderr[:300]}")
    return _parse_rating(out.stdout)


def pick_backend(dry_run: bool):
    if dry_run:
        return None
    if os.environ.get("ANTHROPIC_API_KEY"):
        model = os.environ.get("CALIBRATE_MODEL", "claude-haiku-4-5-20251001")
        return lambda p: rate_via_api(p, model)
    if shutil.which("claude"):
        return rate_via_cli
    raise SystemExit(
        "No model backend: set ANTHROPIC_API_KEY or install the `claude` CLI.\n"
        "(Tonight's content/ai_difficulty.json was produced by a Claude agent fan-out.)"
    )


# ---- tag application ------------------------------------------------------

def apply_tags(col_path: str, ratings: dict[str, dict]) -> None:
    """Write `aidiff::NN` onto each note carrying the matching `id::<item_id>` tag."""
    sys.path.insert(0, str(REPO / "anki" / "out" / "pylib"))
    from anki.collection import Collection  # type: ignore

    col = Collection(col_path)
    try:
        applied = 0
        for item_id, r in ratings.items():
            nids = col.find_notes(f'tag:id::{item_id}')
            for nid in nids:
                note = col.get_note(nid)
                note.tags = [t for t in note.tags if not t.startswith("aidiff::")]
                note.tags.append(f"aidiff::{r['ai_difficulty']}")
                col.update_note(note)
                applied += 1
        print(f"applied aidiff:: tags to {applied} notes")
    finally:
        col.close()


# ---- main -----------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description="AI difficulty calibration")
    ap.add_argument("--only", help="rate only this item id")
    ap.add_argument("--force", action="store_true", help="re-rate already-rated items")
    ap.add_argument("--dry-run", action="store_true", help="print prompts, no model call")
    ap.add_argument("--apply-tags", metavar="COLLECTION", help="write aidiff:: tags to this .anki2")
    args = ap.parse_args()

    items = load_items()
    sidecar: dict[str, dict] = {}
    if SIDECAR_PATH.exists():
        sidecar = json.loads(SIDECAR_PATH.read_text())

    if args.apply_tags:
        if not sidecar:
            raise SystemExit("no ratings in ai_difficulty.json yet; run calibration first")
        apply_tags(args.apply_tags, sidecar)
        return

    backend = pick_backend(args.dry_run)
    todo = [args.only] if args.only else list(items)
    for item_id in todo:
        if item_id not in items:
            print(f"  skip {item_id}: not in items.json", file=sys.stderr)
            continue
        if not args.force and item_id in sidecar and not args.dry_run:
            continue
        prompt = build_prompt(items[item_id])
        if args.dry_run:
            print(f"===== {item_id} =====\n{prompt}\n")
            continue
        try:
            r = backend(prompt)
        except Exception as e:  # noqa: BLE001 - report and continue the batch
            print(f"  {item_id}: FAILED ({e})", file=sys.stderr)
            continue
        r["rubric_version"] = RUBRIC_VERSION
        sidecar[item_id] = r
        print(f"  {item_id}: {r['ai_difficulty']:3d}  {r['ai_difficulty_reason'][:70]}")

    if not args.dry_run:
        SIDECAR_PATH.write_text(json.dumps(sidecar, indent=2, sort_keys=True) + "\n")
        print(f"\nwrote {len(sidecar)} ratings -> {SIDECAR_PATH.relative_to(REPO)}")


if __name__ == "__main__":
    main()
